---

influxdb_key: https://repos.influxdata.com/influxdb.key
influxdb_repo: deb https://repos.influxdata.com/debian bullseye stable

influxdb_user: "e-tag"
influxdb_password: "3V5a7n8#"
influxdb_ip_address: "{{ ansible_hostname }}"
influxdb_bucket: "eslhwdb"
influxdb_org: "e-tag"
influxdb_etc_dir: /etc/influxdb/
#influxdb_enc_algo : "Ed25519"

influxdb_systemd: /lib/systemd/system/influxdb.service

#influxdb_pvt_dir: /etc/influxdb/private
#influxdb_csr_dir: /etc/influxdb/csr
#influxdb_certs_dir: /etc/influxdb/certs

#influxdb_pem: ansible.com.pem
#influxdb_csr: ansible.com.csr
#influxdb_crt: ansible.com.crt

# if using self signed certificate and want to skip verification of the certificate, set the below variable true
#selfsigned: true
